### ISSUE TITLE
Using of tryTo breaks ui runner

### ISSUE THREAD

**Issue by Xotabu4** [codeceptjs/ui#123]
#### What are you trying to achieve?

Using of tryTo breaks ui runner

#### What do you get instead?

> Provide console output if related.

```bash
     Cannot set property 'id' of undefined
      at RealtimeReporterHelper._emitMetaStepChangedIfNecessary (node_modules/@codeceptjs/ui/lib/codeceptjs/realtime-reporter.helper.js:266:29)
      at recorder.add (node_modules/@codeceptjs/ui/lib/codeceptjs/realtime-reporter.helper.js:135:14)
```

> Provide test source code if related:

```js
    const isSubmitSuccessful = await tryTo(() =>
      this.waitForElement('button.progress-loading.state-success', 2)
    );
    if (!isSubmitSuccessful) {
      this.click(signUpId('submit'));
    }
```

### Environment info

- Copy and paste your environment info by using `npx codeceptjs info`

```js


 Environment information:-

codeceptVersion:  "3.0.6"
nodeInfo:  10.13.0
osInfo:  macOS 10.15.7
cpuInfo:  (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
chromeInfo:  89.0.4389.114
edgeInfo:  Not Found
firefoxInfo:  Not Found
safariInfo:  14.0.3
helpers:  {
 "Playwright": {
  "url": "http://localhost:3000/",
  "browser": "chromium",
  "show": true,
  "chromium": {
   "headless": false,
   "defaultViewport": null,
   "args": [
    "--use-fake-device-for-media-stream",
    "--use-fake-ui-for-media-stream"
   ]
  }
 }
}
plugins:  {
 "screenshotOnFail": {
  "enabled": true
 },
 "retryFailedStep": {
  "enabled": true,
  "retries": 2
 },
 "autoDelay": {
  "enabled": true
 },
 "tryTo": {
  "enabled": true
 },
 "retry": {
  "enabled": true,
  "require": "./utils/plugins/retry",
  "retries": 2
 }
}
```

**Comment by Xotabu4** [comment]
This might be related, getting same error on calling moveTo command

![image](https://user-images.githubusercontent.com/3033972/116087747-da795280-a6a9-11eb-88f2-998b66fbacdb.png)

**Comment by BorisOsipov** [comment]
@Xotabu4 probably fixed in https://github.com/codeceptjs/ui/pull/119
