### ISSUE TITLE
When writing test cases using ui, browser has been closed

### ISSUE THREAD

**Issue by maojunxyz** [codeceptjs/ui#159]
#### What are you trying to achieve?

I try to use write test  cases on codecept-ui.

#### What do you get instead?

When I use ui to write tests for use, the browser closes automatically. I can't continue executing the use case I just wrote.

![image](https://user-images.githubusercontent.com/28778042/141938073-b1bde782-f37d-427a-96e2-400ab9ed110a.png)

```powershell
npx codecept-ui --app
🌟 CodeceptUI started!
👉 Open http://localhost:3333 to see CodeceptUI in a browser



Application window opened, switch to it to run tests...
CodeceptJS v3.1.3
Using test root "C:\Users\king\tests\palywright\t2\t3"

new test --
Error processing test.start event:
TypeError: test.tags is not iterable
    at EventEmitter.<anonymous> (C:\Users\king\tests\palywright\node_modules\codeceptjs\lib\plugin\allure.js:208:28)
    at EventEmitter.emit (events.js:327:22)
    at Object.emit (C:\Users\king\tests\palywright\node_modules\codeceptjs\lib\event.js:145:28)
    at Context.test.fn (C:\Users\king\tests\palywright\node_modules\codeceptjs\lib\scenario.js:56:13)
    at callFnAsync (C:\Users\king\tests\palywright\node_modules\mocha\lib\runnable.js:386:21)
    at Test.Runnable.run (C:\Users\king\tests\palywright\node_modules\mocha\lib\runnable.js:330:7)
    at Runner.runTest (C:\Users\king\tests\palywright\node_modules\mocha\lib\runner.js:621:10)
    at C:\Users\king\tests\palywright\node_modules\mocha\lib\runner.js:745:12
    at next (C:\Users\king\tests\palywright\node_modules\mocha\lib\runner.js:538:14)
    at C:\Users\king\tests\palywright\node_modules\mocha\lib\runner.js:548:7
Error processing test.passed event:
TypeError: Cannot convert undefined or null to object
writing C:\Users\king\tests\palywright\t2\t3\output\coverage\new_test_a_1637046479.coverage.json
Remote Interactive shell started
 I.CMD click("百度一下")
Error: Target page, context or browser has been closed
    at DispatcherConnection.dispatch (C:\Users\king\tests\palywright\node_modules\playwright\node_modules\playwright-core\lib\dispatchers\dispatcher.js:247:49)
    at Immediate._onImmediate (C:\Users\king\tests\palywright\node_modules\playwright\node_modules\playwright-core\lib\inProcessFactory.js:52:83)
    at processImmediate (internal/timers.js:461:21)
 FAIL  page.$$: Target page, context or browser has been closed I.Unhandled rejection
Unhandled rejectionUnhandled rejection
Unhandled rejection
Unhandled rejection
Unhandled rejection
 I.
```

### Environment info

- Copy and paste your environment info by using `npx codeceptjs info`

```js

 Environment information:-

codeceptVersion:  "3.1.3"
nodeInfo:  14.16.0
osInfo:  Windows 10 10.0.22000
cpuInfo:  (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
chromeInfo:  Not Found
edgeInfo:  Spartan (44.22000.120.0),Chromium (95.0.1020.53)
firefoxInfo:  N/A
safariInfo:  N/A
helpers:  {
 "Playwright": {
  "url": "https://baidu.com",
  "show": true,
  "browser": "chromium",
  "video": true,
  "keepVideoForPassedTests": true,
  "waitForNavigation": "load",
  "waitForAction": 1500,
  "keepCookies": true
 }
}
plugins:  {
 "screenshotOnFail": {
  "enabled": true
 },
 "pauseOnFail": {},
 "retryFailedStep": {
  "enabled": true
 },
 "tryTo": {
  "enabled": true
 },
 "autoDelay": {
  "enabled": true
 },
 "autoLogin": {
  "enabled": true,
  "saveToFile": true,
  "inject": "loginAs",
  "users": {
   "admin": {}
  }
 },
 "allure": {
  "enabled": true
 },
 "stepByStepReport": {
  "enabled": true,
  "deleteSuccessful": false,
  "screenshotsForAllureReport": true
 },
 "coverage": {
  "enabled": true,
  "uniqueFileName": true
 }
}
***************************************
If you have questions ask them in our Slack: shorturl.at/cuKU8
Or ask them on our discussion board: https://codecept.discourse.group/
Please copy environment info when you report issues on GitHub: https://github.com/Codeception/CodeceptJS/issues
***************************************
```

**Comment by maojunxyz** [comment]
Add the `pause()` action to solve
