### ISSUE TITLE
Missing UUID declaration in package.json

### ISSUE THREAD

**Issue by Sata51** [codeceptjs/ui#91]
#### What are you trying to achieve?

Run codecept-ui

#### What do you get instead?

```bash
yarn run v1.22.4
$ codecept-ui
internal/modules/cjs/loader.js:497
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /node_modules/uuid/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/@codeceptjs/ui/lib/codeceptjs/console-recorder.helper.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Environment info

```js
codeceptVersion:  "2.6.6"
nodeInfo:  14.3.0
osInfo:  Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
cpuInfo:  (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
chromeInfo:  83.0.4103.116
edgeInfo:  N/A
firefoxInfo:  78.0.1
safariInfo:  N/A
helpers:  {
 "WebDriver": {
  "url": "http://localhost/",
  "browser": "chrome",
  "host": "127.0.0.1",
  "port": 4444,
  "restart": false,
  "smartWait": 5000,
  "windowSize": "360x683",
  "desiredCapabilities": {
   "chromeOptions": {
    "args": [
     "--disable-gpu",
     "--no-sandbox"
    ]
   }
  }
 }
}
plugins:  {
 "screenshotOnFail": {
  "enabled": true
 },
 "retryFailedStep": {
  "enabled": true
 },
 "wdio": {
  "enabled": true,
  "services": [
   "selenium-standalone"
  ]
 }
}
```

We are using [the uuid package](https://www.npmjs.com/package/uuid). You are using some uuid package too in `console-recorder.helper.js` but since there is no dependency declared in the `package.json`. When running codecept-ui it try to use the installed package and crash

**Comment by DavertMik** [comment]
Thanks! I added it
