### ISSUE TITLE
/api/actions: HTTP 500 (missing codeceptjs/docs/webapi/ directory)

### ISSUE THREAD

**Issue by gulench** [codeceptjs/ui#93]
#### What are you trying to achieve?

On the home page, *click* a **test scenario** to *execute* it.

#### What do you get instead?

Though the test scenario passes, I see the following error in the *console*, related to the route [/api/actions](http://localhost:3333/api/actions):

```log
Error: ENOENT: no such file or directory, scandir 'X:\codeceptjs-ui-demo\node_modules\codeceptjs\docs\webapi'
    at Object.readdirSync (fs.js:955:3)
    at module.exports (X:\codeceptjs-ui-demo\node_modules\@codeceptjs\ui\lib\api\list-actions.js:14:6)
    at Layer.handle [as handle_request] (X:\codeceptjs-ui-demo\node_modules\express\lib\router\layer.js:95:5)
    at next (X:\codeceptjs-ui-demo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (X:\codeceptjs-ui-demo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (X:\codeceptjs-ui-demo\node_modules\express\lib\router\layer.js:95:5)
    at X:\codeceptjs-ui-demo\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (X:\codeceptjs-ui-demo\node_modules\express\lib\router\index.js:335:12)
    at next (X:\codeceptjs-ui-demo\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (X:\codeceptjs-ui-demo\node_modules\express\lib\router\index.js:174:3)
```

### Environment info

```js
codeceptVersion:  "3.0.0-beta.4"
nodeInfo:  12.18.3
osInfo:  Windows 10 10.0.18363
cpuInfo:  (4) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
chromeInfo:  85.0.4183.83
edgeInfo:  Spartan (44.18362.449.0)
firefoxInfo:  N/A
safariInfo:  N/A
helpers:  {
 "WebDriver": {
  "url": "http://localhost",
  "browser": "chrome"
 }
}
plugins:  {
 "screenshotOnFail": {
  "enabled": true
 },
 "retryFailedStep": {
  "enabled": true
 },
 "wdio": {
  "enabled": true,
  "services": [
   "selenium-standalone"
  ]
 }
}
```

**Comment by gulench** [comment]
https://github.com/codeceptjs/CodeceptJS/blob/ee5671bd1a32e852adbf62b7abebce8e30f573e6/package.json#L24-L26

The package distribution for the [codeceptjs-v3.0](https://github.com/codeceptjs/CodeceptJS/tree/codeceptjs-v3.0) branch contains a sub-set of the `docs` directory. It contains only the `docs/**/*.md` files, and does not include the `docs/webapi` directory with the `*.mustache` files (that is expected by [codeceptjs-ui v0.4.0](https://www.npmjs.com/package/@codeceptjs/ui/v/0.4.0)).
